// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LA6hYAobNl_6DLk0HQ1nZSOqCSgYrSM',
    appId: '1:663765526403:web:aea3b1fb1407de25b7f8b6',
    messagingSenderId: '663765526403',
    projectId: 'healthcheckup-134a1',
    authDomain: 'healthcheckup-134a1.firebaseapp.com',
    storageBucket: 'healthcheckup-134a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQvAxTdk2vKyWOB2M8wObJfciA5U6wvY',
    appId: '1:663765526403:android:745b2c6915a64217b7f8b6',
    messagingSenderId: '663765526403',
    projectId: 'healthcheckup-134a1',
    storageBucket: 'healthcheckup-134a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARNzpEXY-VLpFYWa8KN4SNRh8odnP-7m8',
    appId: '1:663765526403:ios:be5005181a0588aab7f8b6',
    messagingSenderId: '663765526403',
    projectId: 'healthcheckup-134a1',
    storageBucket: 'healthcheckup-134a1.appspot.com',
    iosBundleId: 'com.example.alemenoHealthCheckup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARNzpEXY-VLpFYWa8KN4SNRh8odnP-7m8',
    appId: '1:663765526403:ios:4daef79754a056a6b7f8b6',
    messagingSenderId: '663765526403',
    projectId: 'healthcheckup-134a1',
    storageBucket: 'healthcheckup-134a1.appspot.com',
    iosBundleId: 'com.example.alemenoHealthCheckup.RunnerTests',
  );
}
