// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYv1FXa0nYYvlNneyvuBnZsnpdxYlea2A',
    appId: '1:817926074445:web:8140e8e0cf0bc966c86c04',
    messagingSenderId: '817926074445',
    projectId: 'health-checkup-8b2d4',
    authDomain: 'health-checkup-8b2d4.firebaseapp.com',
    storageBucket: 'health-checkup-8b2d4.appspot.com',
    measurementId: 'G-GGPX5X72JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUgI6Ahiy9CBOG8TanvOvuj3YZXlBoPs',
    appId: '1:817926074445:android:bd400570e8e96f6bc86c04',
    messagingSenderId: '817926074445',
    projectId: 'health-checkup-8b2d4',
    storageBucket: 'health-checkup-8b2d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdrW1AsS68yhmfQe50zIJMV_L0GHLdGc',
    appId: '1:817926074445:ios:9bc5a30cbf5d8804c86c04',
    messagingSenderId: '817926074445',
    projectId: 'health-checkup-8b2d4',
    storageBucket: 'health-checkup-8b2d4.appspot.com',
    iosBundleId: 'com.example.alemenoHealthCheckup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdrW1AsS68yhmfQe50zIJMV_L0GHLdGc',
    appId: '1:817926074445:ios:9ec786a4a63fbfc8c86c04',
    messagingSenderId: '817926074445',
    projectId: 'health-checkup-8b2d4',
    storageBucket: 'health-checkup-8b2d4.appspot.com',
    iosBundleId: 'com.example.alemenoHealthCheckup.RunnerTests',
  );
}
